insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'sarvam-ai',
    'Sarvam AI',
    'https://www.sarvam.ai',
    'Builds Indian-language foundation models and sovereign AI infrastructure for enterprises and government.',
    'Core Labs',
    'Indiranagar, Bengaluru, Karnataka 560038',
    'bengaluru',
    12.9784,
    77.6408,
    2023,
    'https://www.google.com/s2/favicons?domain=sarvam.ai&sz=128',
    'default',
    'https://en.wikipedia.org/wiki/Sarvam_AI'
  ),
  (
    'krutrim',
    'Krutrim',
    'https://www.olakrutrim.com',
    'Builds Indic large language models, cloud AI services and custom silicon under the Ola group.',
    'Core Labs',
    'Koramangala Industrial Layout, Hosur Road, Bengaluru, Karnataka 560095',
    'bengaluru',
    12.9352,
    77.6245,
    2023,
    'https://www.google.com/s2/favicons?domain=olakrutrim.com&sz=128',
    'default',
    'https://inc42.com/company/ola-krutrim/'
  ),
  (
    'gnani-ai',
    'Gnani.ai',
    'https://www.gnani.ai',
    'Builds multilingual speech models and voice AI agents for enterprise contact centres.',
    'Agents',
    'Basavanagudi, Bengaluru, Karnataka 560004',
    'bengaluru',
    12.9422,
    77.5738,
    2016,
    'https://www.google.com/s2/favicons?domain=gnani.ai&sz=128',
    'default',
    'https://www.gnani.ai/about-us'
  ),
  (
    'entropik',
    'Entropik',
    'https://www.entropik.io',
    'Emotion AI research platform using facial coding, eye tracking and voice analysis for consumer insights.',
    'Vertical AI',
    'Indiranagar, Bengaluru, Karnataka 560038',
    'bengaluru',
    12.9719,
    77.6412,
    2016,
    'https://www.google.com/s2/favicons?domain=entropik.io&sz=128',
    'default',
    'https://yourstory.com/2023/03/bengaluru-based-entropik-ai-startup-helping-brands-tap-into-human-emotion'
  ),
  (
    'niramai',
    'Niramai Health Analytix',
    'https://niramai.com',
    'Radiation-free breast cancer screening using thermal imaging and machine learning.',
    'Vertical AI',
    'Innova Pearl, 5th Block, Koramangala Industrial Layout, Bengaluru, Karnataka 560095',
    'bengaluru',
    12.9345,
    77.627,
    2016,
    'https://www.google.com/s2/favicons?domain=niramai.com&sz=128',
    'default',
    'https://niramai.com/contact/'
  ),
  (
    'sigtuple',
    'SigTuple Technologies',
    'https://sigtuple.com',
    'Automates microscopy-based medical diagnostics with robotic slide scanners and AI image analysis.',
    'Vertical AI',
    '14th Cross Road, Sector 6, HSR Layout, Bengaluru, Karnataka 560102',
    'bengaluru',
    12.9121,
    77.6446,
    2015,
    'https://www.google.com/s2/favicons?domain=sigtuple.com&sz=128',
    'default',
    'https://sigtuple.com/about/'
  ),
  (
    'dozee',
    'Dozee',
    'https://dozeehealth.ai',
    'Contactless remote patient monitoring that reads vitals from a sensor placed under the mattress.',
    'Vertical AI',
    'Indiranagar, Bengaluru, Karnataka 560008',
    'bengaluru',
    12.975,
    77.639,
    2015,
    'https://www.google.com/s2/favicons?domain=dozeehealth.ai&sz=128',
    'default',
    'https://www.biospectrumindia.com/features/85/19324/startupoftheday-7-dozee-turtle-shell-technologies-pvt-ltd.html'
  ),
  (
    'cropin',
    'Cropin Technology Solutions',
    'https://www.cropin.com',
    'Agritech SaaS using satellite imagery and AI to monitor crops and forecast yields for agribusinesses.',
    'Vertical AI',
    '16th Main, BTM Layout 1st Stage, Bengaluru, Karnataka 560029',
    'bengaluru',
    12.9166,
    77.6101,
    2010,
    'https://www.google.com/s2/favicons?domain=cropin.com&sz=128',
    'default',
    'https://www.cropin.com/connect/'
  ),
  (
    'wysa',
    'Wysa',
    'https://www.wysa.com',
    'AI chatbot app for mental health self-care, paired with human therapist support.',
    'Consumer AI',
    '2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    'bengaluru',
    12.98,
    77.645,
    2015,
    'https://www.google.com/s2/favicons?domain=wysa.com&sz=128',
    'default',
    'https://legal.wysa.io/research/privacy-policy'
  ),
  (
    'whatfix',
    'Whatfix',
    'https://whatfix.com',
    'Digital adoption platform that layers in-app guidance, training and analytics onto enterprise software.',
    'Infra',
    '18th Cross Road, Sector 3, HSR Layout, Bengaluru, Karnataka 560102',
    'bengaluru',
    12.9165,
    77.639,
    2014,
    'https://www.google.com/s2/favicons?domain=whatfix.com&sz=128',
    'default',
    'https://whatfix.com/about-us/'
  ),
  (
    'hasura',
    'Hasura',
    'https://hasura.io',
    'Generates GraphQL and REST APIs over databases and services for application developers.',
    'Devtools',
    'Koramangala, Bengaluru, Karnataka 560095',
    'bengaluru',
    12.931,
    77.628,
    2017,
    'https://www.google.com/s2/favicons?domain=hasura.io&sz=128',
    'default',
    'https://hasura.io/about/'
  ),
  (
    'postman',
    'Postman',
    'https://www.postman.com',
    'API development platform for designing, testing, documenting and collaborating on APIs.',
    'Devtools',
    '6th Main Road, Indiranagar, Bengaluru, Karnataka 560038',
    'bengaluru',
    12.976,
    77.642,
    2014,
    'https://www.google.com/s2/favicons?domain=postman.com&sz=128',
    'default',
    'https://www.postman.com/company/about-postman/'
  ),
  (
    'simplismart',
    'Simplismart',
    'https://simplismart.ai',
    'Inference platform for deploying and scaling open-source language, speech and image models.',
    'Infra',
    'Residency Road, Bengaluru, Karnataka 560025',
    'bengaluru',
    12.967,
    77.601,
    2022,
    'https://www.google.com/s2/favicons?domain=simplismart.ai&sz=128',
    'default',
    'https://www.forbes.com/sites/davidprosser/2024/10/17/how-simplismart-plans-to-power-the-ubiquity-of-generative-ai/'
  ),
  (
    'clearfeed',
    'ClearFeed',
    'https://clearfeed.ai',
    'AI helpdesk that turns Slack and Microsoft Teams channels into tracked support request queues.',
    'Agents',
    'HSR Layout, Bengaluru, Karnataka 560102',
    'bengaluru',
    12.908,
    77.648,
    2021,
    'https://www.google.com/s2/favicons?domain=clearfeed.ai&sz=128',
    'default',
    'https://inc42.com/company/clearfeed/'
  ),
  (
    'nurix-ai',
    'Nurix AI',
    'https://www.nurix.ai',
    'Builds custom voice and reasoning AI agents that run customer support and back-office workflows.',
    'Agents',
    'HSR Layout, Bengaluru, Karnataka 560102',
    'bengaluru',
    12.9145,
    77.65,
    2024,
    'https://www.google.com/s2/favicons?domain=nurix.ai&sz=128',
    'default',
    'https://entrackr.com/2024/09/mukesh-bansals-nurix-ai-bags-27-5-mn-from-accel-general-catalyst-meraki-labs/'
  ),
  (
    'vahan-ai',
    'Vahan.ai',
    'https://vahan.ai',
    'AI recruiting platform hiring blue-collar workers for gig and logistics firms via WhatsApp and voice.',
    'Vertical AI',
    'Koramangala, Bengaluru, Karnataka 560034',
    'bengaluru',
    12.938,
    77.622,
    2016,
    'https://www.google.com/s2/favicons?domain=vahan.ai&sz=128',
    'default',
    'https://yourstory.com/2024/09/vahanai-secures-10-million-funding-in-series-b-blue-collar-workforce'
  ),
  (
    'corover-ai',
    'CoRover.ai',
    'https://corover.ai',
    'Conversational AI assistants built on its BharatGPT model, serving Indian enterprises and government.',
    'Agents',
    'Hosur Road, HSR Layout area, Bengaluru, Karnataka 560068',
    'bengaluru',
    12.9,
    77.635,
    2016,
    'https://www.google.com/s2/favicons?domain=corover.ai&sz=128',
    'default',
    'https://indiaai.gov.in/news/conversational-ai-startup-corover-receives-funding-from-canbank-venture-capital'
  ),
  (
    'qpiai',
    'QpiAI',
    'https://qpiai.tech',
    'Full-stack quantum computing and AI company building quantum hardware and AI/HPC software.',
    'Infra',
    'Karle Town Center, Nagavara, Bengaluru, Karnataka 560045',
    'bengaluru',
    13.043,
    77.622,
    2019,
    'https://www.google.com/s2/favicons?domain=qpiai.tech&sz=128',
    'default',
    'https://techcrunch.com/2025/07/16/india-eyes-global-quantum-computer-push-and-qpiai-is-its-chosen-vehicle'
  ),
  (
    'truefoundry',
    'TrueFoundry',
    'https://www.truefoundry.com',
    'Platform for deploying, serving and governing machine learning and LLM workloads across clouds.',
    'Infra',
    'Bengaluru, Karnataka',
    'bengaluru',
    12.9716,
    77.5946,
    2021,
    'https://www.google.com/s2/favicons?domain=truefoundry.com&sz=128',
    'default',
    'https://yourstory.com/2025/02/truefoundry-raises-19-million-series-a-funding-led-by-intel-capital'
  ),
  (
    'yellow-ai',
    'Yellow.ai',
    'https://yellow.ai',
    'Enterprise conversational AI platform automating customer service across chat, voice and email.',
    'Agents',
    '1st Cross Road, 5th Block, Koramangala, Bengaluru, Karnataka 560034',
    'bengaluru',
    12.9345,
    77.618,
    2016,
    'https://www.google.com/s2/favicons?domain=yellow.ai&sz=128',
    'default',
    'https://yellow.ai/about-us/'
  ),
  (
    'observe-ai',
    'Observe.AI',
    'https://www.observe.ai',
    'Analyzes and automates contact centre conversations to coach agents and improve customer service.',
    'Vertical AI',
    'Bellandur, Bengaluru, Karnataka 560103',
    'bengaluru',
    12.926,
    77.6762,
    2017,
    'https://www.google.com/s2/favicons?domain=observe.ai&sz=128',
    'default',
    'https://www.observe.ai/about-us'
  ),
  (
    'skit-ai',
    'Skit.ai',
    'https://www.skit.ai',
    'Voice AI that automates outbound debt collection and accounts-receivable calls.',
    'Vertical AI',
    'Indiranagar, Bengaluru, Karnataka 560038',
    'bengaluru',
    12.982,
    77.638,
    2016,
    'https://www.google.com/s2/favicons?domain=skit.ai&sz=128',
    'default',
    'https://www.prnewswire.com/in/news-releases/voice-ai-company-vernacular-ai-rebrands-to-skit-secures-series-b-round-of-usd-23-million-from-westbridge-capital-897074893.html'
  ),
  (
    'ultrahuman',
    'Ultrahuman',
    'https://www.ultrahuman.com',
    'Smart ring and metabolic tracking wearables with AI-driven health and sleep insights.',
    'Consumer AI',
    'Hosur Main Road, Bommanahalli, Bengaluru, Karnataka 560068',
    'bengaluru',
    12.8996,
    77.62,
    2019,
    'https://www.google.com/s2/favicons?domain=ultrahuman.com&sz=128',
    'default',
    'https://en.wikipedia.org/wiki/Ultrahuman'
  )
on conflict (city, slug) do nothing;
