insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'sanctuary-ai',
    'Sanctuary AI',
    'https://www.sanctuary.ai',
    'Physical AI company building humanoid robots for general-purpose work in real-world environments.',
    'Core Labs',
    '1825 Quebec Street, Vancouver, BC V5T 2Z3',
    'vancouver',
    49.2687941,
    -123.1029915,
    2018,
    null,
    'default',
    'https://www.sanctuary.ai/'
  ),
  (
    'light-ai',
    'Light AI',
    'https://light.ai',
    'Smartphone-based diagnostic platform using AI to help distinguish bacterial from viral infections.',
    'Vertical AI',
    '1055 West Georgia Street, Suite 1500, Vancouver, BC V6E 4N7',
    'vancouver',
    49.2853000,
    -123.1215835,
    2010,
    null,
    'default',
    'https://light.ai/privacy-policy/'
  ),
  (
    'inverted-ai',
    'Inverted AI',
    'https://www.inverted.ai',
    'Simulation API for generating realistic traffic agents and scenarios for autonomous vehicle testing.',
    'Infra',
    '151 West Hastings Street, Vancouver, BC V6B 1H4',
    'vancouver',
    49.2825473,
    -123.1088443,
    2018,
    null,
    'default',
    'https://www.cbinsights.com/company/inverted-ai'
  ),
  (
    'variational-ai',
    'Variational AI',
    'https://variational.ai',
    'Generative AI platform for designing novel small-molecule therapeutics.',
    'Vertical AI',
    '1825 Quebec Street, #201, Vancouver, BC V5T 2Z3',
    'vancouver',
    49.2687941,
    -123.1029915,
    2019,
    null,
    'default',
    'https://variational.ai/contact/'
  ),
  (
    'apera-ai',
    'Apera AI',
    'https://apera.ai',
    '4D vision platform that helps industrial robots perceive, pick, and manipulate parts in production.',
    'Vertical AI',
    '134 Abbott Street, Suite 501, Vancouver, BC V6B 2K4',
    'vancouver',
    49.2840979,
    -123.1060205,
    2016,
    null,
    'default',
    'https://apera.ai/wp-content/uploads/Eguide-brochure-Apera-AI.pdf'
  ),
  (
    'vrify',
    'VRIFY',
    'https://vrify.com',
    'AI-assisted mineral discovery platform for exploration teams and mining operators.',
    'Vertical AI',
    '1075 West Georgia Street, Suite 2360, Vancouver, BC V6E 3C9',
    'vancouver',
    49.2858181,
    -123.1222990,
    2017,
    null,
    'default',
    'https://vrify.com/contact/'
  ),
  (
    'ad-auris',
    'Ad Auris',
    'https://www.adauris.ai',
    'AI platform that turns written content into audio experiences for publishers and marketers.',
    'Vertical AI',
    '1565 Burnaby Street, Vancouver, BC',
    'vancouver',
    49.2844781,
    -123.1392547,
    2020,
    null,
    'default',
    'https://www.adauris.ai/contact'
  ),
  (
    'bayes-studio',
    'Bayes Studio',
    'https://bayesstudio.com',
    'AI systems for wildfire detection and environmental monitoring across resilience operations.',
    'Vertical AI',
    '2366 Main Mall, Office 162, Vancouver, BC V6T 1Z4',
    'vancouver',
    49.2612140,
    -123.2488437,
    2022,
    null,
    'default',
    'https://bayesstudio.com/contact/'
  ),
  (
    'ondeck-ai',
    'OnDeck AI',
    'https://www.ondeck.fish',
    'Vision AI platform for analyzing video and aquaculture monitoring workflows without manual review at scale.',
    'Infra',
    '2366 Main Mall, #289, Vancouver, BC V6T 1Z4',
    'vancouver',
    49.2612140,
    -123.2488437,
    2022,
    null,
    'default',
    'https://www.ondeck.fish/'
  ),
  (
    'metaspectral',
    'Metaspectral',
    'https://metaspectral.com',
    'Hyperspectral computer vision platform for identifying materials, defects, and chemical composition.',
    'Infra',
    '319 West Hastings Street, #400, Vancouver, BC V6B 1H6',
    'vancouver',
    49.2832371,
    -123.1100711,
    2018,
    null,
    'default',
    'https://metaspectral.com/'
  ),
  (
    'ringable-ai',
    'Ringable AI',
    'https://ringable.ai',
    'Voice AI agents for support, troubleshooting, and account workflows over the phone.',
    'Agents',
    '1965 West 4th Avenue, Suite 202, Vancouver, BC V6J 1M8',
    'vancouver',
    49.2684054,
    -123.1496639,
    2023,
    null,
    'default',
    'https://www.cbinsights.com/company/ringable'
  ),
  (
    'thisfish',
    'ThisFish',
    'https://this.fish',
    'AI-powered traceability and quality intelligence platform for seafood processors and suppliers.',
    'Vertical AI',
    '2002-125 Milross Avenue, Vancouver, BC V6A 0A1',
    'vancouver',
    49.2764329,
    -123.1017435,
    2017,
    null,
    'default',
    'https://this.fish/'
  ),
  (
    'intuitive-ai',
    'Intuitive AI',
    'https://www.intuitiveai.ca',
    'AI recycling assistant and waste analytics platform for sorting, measurement, and zero-waste operations.',
    'Vertical AI',
    '555 West Hastings Street, #1200, Vancouver, BC V6B 4N6',
    'vancouver',
    49.2846668,
    -123.1119122,
    2017,
    null,
    'default',
    'https://www.intuitiveai.ca/'
  ),
  (
    'verifyiq',
    'VERIFYiQ',
    'https://www.verifyiq.co',
    'Automated quality control platform for reviewing bookkeeping and accounting files before delivery.',
    'Vertical AI',
    '510 West Hastings Street, Unit 803, Vancouver, BC V6B 1L8',
    'vancouver',
    49.2841133,
    -123.1123702,
    2024,
    null,
    'default',
    'https://www.verifyiq.co/'
  )
on conflict (city, slug) do update
set
  name = excluded.name,
  website = excluded.website,
  short_description = excluded.short_description,
  category = excluded.category,
  location_label = excluded.location_label,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  founded = excluded.founded,
  logo_url = excluded.logo_url,
  map_sprite = excluded.map_sprite,
  source_url = excluded.source_url;
